"""1.3.2

Revision ID: 6766a9cd1d4b
Revises: a933386acbad
Create Date: 2026-04-10 11:50:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, Integer, Text, String, Sequence
import json


# revision identifiers, used by Alembic.
revision = '6766a9cd1d4b'
down_revision = 'a933386acbad'
branch_labels = None
depends_on = None


def has_table(table_name):
    """检查表是否已存在"""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not has_table('MEDIASERVER'):
        op.create_table(
            'MEDIASERVER',
            Column('ID', Integer, Sequence('ID'), primary_key=True),
            Column('NAME', String(255), nullable=False),
            Column('ENABLED', Integer, nullable=False, server_default='0'),
            Column('CONFIG', Text),
            Column('IS_DEFAULT', Integer, nullable=False, server_default='0'),
            Column('NOTE', Text),
        )
        op.create_index('ix_MEDIASERVER_NAME', 'MEDIASERVER', ['NAME'], unique=False)

    # 尝试从配置文件迁移现有媒体服务器配置到数据库
    try:
        import os
        config_path = os.environ.get('NASTOOL_CONFIG')
        if config_path:
            import ruamel.yaml
            with open(config_path, mode='r', encoding='utf-8') as cf:
                cfg = ruamel.yaml.YAML().load(cf)
            if cfg:
                media_server_type = cfg.get('media', {}).get('media_server', 'emby')
                server_map = {
                    'emby': cfg.get('emby'),
                    'jellyfin': cfg.get('jellyfin'),
                    'plex': cfg.get('plex'),
                    'fnos': cfg.get('fnos'),
                }
                conn = op.get_bind()
                for name, config in server_map.items():
                    if config:
                        enabled = 1 if name == media_server_type else 0
                        is_default = 1 if name == media_server_type else 0
                        # 检查是否已存在
                        result = conn.execute(
                            sa.text("SELECT ID FROM MEDIASERVER WHERE NAME = :name"),
                            {"name": name}
                        ).fetchone()
                        if not result:
                            conn.execute(
                                sa.text(
                                    "INSERT INTO MEDIASERVER (NAME, ENABLED, CONFIG, IS_DEFAULT) "
                                    "VALUES (:name, :enabled, :config, :is_default)"
                                ),
                                {
                                    "name": name,
                                    "enabled": enabled,
                                    "config": json.dumps(config) if config else None,
                                    "is_default": is_default,
                                }
                            )
    except Exception:
        pass

    # 修改 SEARCH_RESULT_INFO 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table('SEARCH_RESULT_INFO') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(2048),
                existing_type=sa.String(255)
            )
    except Exception:
        pass

    # 修改 SEARCH_RESULT_INFO 表的 SIZE 字段类型为 BigInteger，兼容超过 2GB 的种子大小
    try:
        with op.batch_alter_table('SEARCH_RESULT_INFO') as batch_op:
            batch_op.alter_column(
                'SIZE',
                type_=sa.BigInteger(),
                existing_type=sa.Integer()
            )
    except Exception:
        pass

    # 修改 CONFIG_SITE 表的 SIZE 字段类型为 BigInteger，并转换旧数据
    try:
        conn = op.get_bind()
        # 先读取并转换旧数据
        rows = conn.execute(sa.text("SELECT ID, SIZE FROM CONFIG_SITE")).fetchall()
        for row in rows:
            size_val = row[1]
            if size_val:
                try:
                    size_bytes = int(float(size_val) * 1024 ** 3)
                except (ValueError, TypeError):
                    size_bytes = 0
                conn.execute(
                    sa.text("UPDATE CONFIG_SITE SET SIZE = :size WHERE ID = :id"),
                    {"size": size_bytes, "id": row[0]}
                )
        with op.batch_alter_table('CONFIG_SITE') as batch_op:
            batch_op.alter_column(
                'SIZE',
                type_=sa.BigInteger(),
                existing_type=sa.String(255)
            )
    except Exception:
        pass

    # 修改 SITE_BRUSH_TASK 表的 SEED_SIZE 字段类型为 BigInteger，并转换旧数据
    try:
        conn = op.get_bind()
        rows = conn.execute(sa.text("SELECT ID, SEED_SIZE FROM SITE_BRUSH_TASK")).fetchall()
        for row in rows:
            size_val = row[1]
            if size_val:
                try:
                    size_bytes = int(float(size_val) * 1024 ** 3)
                except (ValueError, TypeError):
                    size_bytes = 0
                conn.execute(
                    sa.text("UPDATE SITE_BRUSH_TASK SET SEED_SIZE = :size WHERE ID = :id"),
                    {"size": size_bytes, "id": row[0]}
                )
        with op.batch_alter_table('SITE_BRUSH_TASK') as batch_op:
            batch_op.alter_column(
                'SEED_SIZE',
                type_=sa.BigInteger(),
                existing_type=sa.String(255)
            )
    except Exception:
        pass

    # 修改 DOWNLOAD_HISTORY 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table('DOWNLOAD_HISTORY') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(2048),
                existing_type=sa.String(512)
            )
    except Exception:
        pass

    # 修改 RSS_TORRENTS 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table('RSS_TORRENTS') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(2048),
                existing_type=sa.String(512)
            )
    except Exception:
        pass

    # 修改 SITE_BRUSH_TORRENTS 表的 ENCLOSURE 字段长度，兼容 magnet 长链接
    try:
        with op.batch_alter_table('SITE_BRUSH_TORRENTS') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(2048),
                existing_type=sa.String(512)
            )
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('SITE_BRUSH_TORRENTS') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(512),
                existing_type=sa.String(2048)
            )
    except Exception:
        pass
    try:
        with op.batch_alter_table('RSS_TORRENTS') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(512),
                existing_type=sa.String(2048)
            )
    except Exception:
        pass
    try:
        with op.batch_alter_table('DOWNLOAD_HISTORY') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(512),
                existing_type=sa.String(2048)
            )
    except Exception:
        pass
    try:
        with op.batch_alter_table('SEARCH_RESULT_INFO') as batch_op:
            batch_op.alter_column(
                'ENCLOSURE',
                type_=sa.String(255),
                existing_type=sa.String(2048)
            )
    except Exception:
        pass
    try:
        with op.batch_alter_table('SEARCH_RESULT_INFO') as batch_op:
            batch_op.alter_column(
                'SIZE',
                type_=sa.Integer(),
                existing_type=sa.BigInteger()
            )
    except Exception:
        pass
    if has_table('MEDIASERVER'):
        op.drop_table('MEDIASERVER')
    # ### end Alembic commands ###
