services:
  nas-tools:
    image: linyuan0213/nas-tools:latest
    ports:
      - 3000:80
    volumes:
      - ./config:/config
      - /你的媒体目录:/你想设置的容器内能见到的目录
    environment:
      - PUID=0
      - PGID=0
      - UMASK=000
      - NT_PORT=3000
    restart: always
    hostname: nas-tools
    container_name: nas-tools
    networks:
      - nas-tools-network
    healthcheck:
      test: "wget -qO- http://localhost/health || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: nas-tools-redis
    volumes:
      - ./config/redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - nas-tools-network

  ocr:
    image: linyuan0213/nas-tools-ocr:latest
    container_name: nas-tools-ocr
    ports:
      - 9300:9300
    restart: always
    networks:
      - nas-tools-network

  chrome:
    image: linyuan0213/nas-tools-chrome:latest
    container_name: nas-tools-chrome
    shm_size: 2g
    environment:
      - VNC_PASSWORD=password
    volumes:
      - ./data:/var/lib/chromium/user_data
    ports:
      - 9850:9850
      - 6080:6080
    restart: always
    networks:
      - nas-tools-network

networks:
  nas-tools-network:
    driver: bridge
    name: nas-tools-network
