services:
  frontend:
    image: linyuan0213/nexus-media-web:latest
    ports:
      - 3000:80
    restart: always
    container_name: nexus-media-web
    networks:
      - nexus-media-network
    depends_on:
      - backend

  backend:
    image: linyuan0213/nexus-media:latest
    ports:
      - 3001:3000
    volumes:
      - ./config:/config
      - /你的媒体目录:/你想设置的容器内能见到的目录
    environment:
      - PUID=0
      - PGID=0
      - UMASK=000
      - NT_PORT=3000
    restart: always
    hostname: nexus-media
    container_name: nexus-media
    networks:
      - nexus-media-network
    healthcheck:
      test: "wget -qO- http://localhost:3000/health || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: nexus-media-redis
    volumes:
      - ./config/redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - nexus-media-network

  ocr:
    image: linyuan0213/nexus-media-ocr:latest
    container_name: nexus-media-ocr
    ports:
      - 9300:9300
    restart: always
    networks:
      - nexus-media-network

  chrome:
    image: linyuan0213/nexus-media-chrome:latest
    container_name: nexus-media-chrome
    shm_size: 2g
    environment:
      - VNC_PASSWORD=password
    volumes:
      - ./data:/var/lib/chromium/user_data
    ports:
      - 9850:9850
      - 6080:6080
    restart: always
    networks:
      - nexus-media-network

networks:
  nexus-media-network:
    driver: bridge
    name: nexus-media-network
